version: '3.8'

services:
  jenkins:
    image: dockerrajmanda/jenkins:latest  # Replace with your Jenkins image name
    container_name: jenkins
    ports:
      - "8081:8080"      # Maps port 8081 on the host to port 8080 in the container
      - "50000:50000"    # Jenkins agent port
    volumes:
      - ~/.ssh:/var/jenkins_home/.ssh  # Mount SSH keys for Git access
      - jenkins_home:/var/jenkins_home  # Persist Jenkins data
    restart: unless-stopped  # Restart policy

volumes:
  jenkins_home:   # Named volume for persistent Jenkins home
